### PR TITLE
Remove usage of save and restore cursor

### PR DESCRIPTION
**Pull request by mptre**
Usage of cursor save and restore capabilities is non-obvious. Moving the
cursor the appropriate number of lines/columns is easier to follow.

While at it, make the query cursor movement a single operation as
opposed of the current implementation which is linear with the number of
characters in the query.

I would appreciate if others could test this change in order to not
introduce any regression.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @mptre, sorry for the late feedback. The code looks great and I agree that it is easier to follow. Thanks for working on this! Pick runs without regressions on my machine.

@teoljungberg Would you mind testing it in your tmux setup that had issues before?

**Comment by teoljungberg** [comment]
@calleerlandsson Looks good after testing this out locally.

**Comment by mptre** [comment]
Thanks for testing, I'm merging now. While at it, time for another
release?

**Comment by calleerlandsson** [comment]
Thanks @mptre! Yes, I think it's time for a release. I'll merge #158 and release.

**Pull request merged**
