### PR TITLE
Use the `CTRL` macro in `sys/ttydefaults.h`

### PR DESCRIPTION
**Pull request by calleerlandsson**
This reduces LOC.

### CODE REVIEW

**Comment by mike-burns** [comment]
How does `sys/ttydefaults.h` get in?

**Comment by calleerlandsson** [comment]
It is included by `sys/termios.h`, which is included by `termios.h`.

**Comment by mike-burns** [comment]
Rad. Thanks for traversing through header files for me.

LGTM. Great cleanup.

**Comment by calleerlandsson** [comment]
Ha! It's always good to know. `-E` to the rescue. I'll merge this.

**Pull request merged**
