### PR TITLE
Automatically disable alternate screen in Vim.

### PR DESCRIPTION
**Pull request by calleerlandsson**
Detect running from within Vim and automatically disable usage of the
alternate screen.

### CODE REVIEW

**Comment by mike-burns** [comment]
I like that there is still the option to force it with `-X`. I'll submit a PR to override it with `-x`, later. LGTN.

**Comment by calleerlandsson** [comment]
I agree. Thanks @mike-burns! Since it isn't that much code I'll add it in this PR.

**Comment by calleerlandsson** [comment]
This is ready for another pass.

**Comment by mike-burns** [comment]
Can you update the manpage to document that it also looks for `$VIM`?

**Comment by calleerlandsson** [comment]
Good point. Done in b1d19e4.

**Comment by mike-burns** [comment]
Looks good to merge.

**Comment by calleerlandsson** [comment]
Great! Merging.

**Pull request merged**
