### PR TITLE
Add test suite

### PR DESCRIPTION
**Pull request by mptre**
Here's something I've been experimenting with lately. The `tests/README.md` file should, hopefully, explain the changes further. Let me know what you think.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @mptre, this looks super cool!

When I tried compiling and running `make test` on my Mac this error is printed.

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C tests
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [test] Error 2
```

Am I missing something?

**Comment by mptre** [comment]
Did you run the autogen.sh script prior make test? Your Makefile is
probably outdated.

On 5 February 2016 at 16:21, Calle Erlandsson <notifications@github.com>
wrote:

> Hey @mptre <https://github.com/mptre>, this looks super cool!
>
> When I tried compiling and running make test on my Mac this error is
> printed.
>
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -C tests
> make[1]: *** No targets specified and no makefile found.  Stop.
> make: *** [test] Error 2
>
> Am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/pick/pull/99#issuecomment-180398531>.
>



-- 
:wq

**Comment by mike-burns** [comment]
1. This is beautiful.

2. Can this make use of the autotools TAP test infrastructure, such that the `check` target (and especially `distcheck` target) run the test suite?

https://www.gnu.org/software/automake/manual/html_node/Use-TAP-with-the-Automake-test-harness.html#Use-TAP-with-the-Automake-test-harness
https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html#Parallel-Test-Harness

It should be as easy as adding `TESTS=test/tests.sh` to `Makefile.am`, or thereabout.

**Comment by calleerlandsson** [comment]
@mptre Yeah, I did run `autogen.sh`. I'm not running GNU make. Could that be it?

**Comment by mptre** [comment]
My bad, forgot to commit the tests/Makefile. I did attempt to make it automake
compatible but it could most probably be improved. I also had to rename the
test-files since the tests/Makefile.in would be recognized as a test-file
otherwise.

On Fri, Feb 05, 2016 at 07:34:00AM -0800, Calle Erlandsson wrote:
> @mptre Yeah, I did run `autogen.sh`. I'm not running GNU make. Could that be it?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/pull/99#issuecomment-180403589

-- 
:wq

**Comment by mptre** [comment]
`tests/test` is being linked against ncurses. Overwriting `AM_LDFLAGS` in `tests/Makefile.am` does not help either. Shouldn't the `src` directory have a separate Makefile?

**Comment by mike-burns** [comment]
This project uses a non-recursive makefile. For some documentation on that, I recommend https://autotools.io/automake/nonrecursive.html .

**Comment by mptre** [comment]
Thanks for the info, `make check` is working by now. I still want to make the
test runner more robust to failures prior merging.

On Mon, Feb 08, 2016 at 11:26:41AM -0800, Mike Burns wrote:
> This project uses a non-recursive makefile. For some documentation on that, I recommend https://autotools.io/automake/nonrecursive.html .
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/pull/99#issuecomment-181464911

-- 
:wq

**Comment by mptre** [comment]
The latest commit adds a timeout to the forked pick process in order to terminate if the process gets stuck or if the test case contains to few keystrokes.

**Comment by calleerlandsson** [comment]
Very cool, @mptre! Running this on Mac OS X 10.11.2, I get a "time limit exceeded" error on `tests/01.in`. I have tried upping the limit on `tests/test.c:136` but it times out regardless of the limit. I interpret this as pick not understanding the input and not exiting.

Adding a `#!/usr/bin/env bash` to `tests/test.sh` fixes the time out on `tests/01.in`. My theory is that this has something to do with how `echo` works across `/bin/sh` and `bash`:

```
sh-3.2$ f=$(grep "^input: " < tests/01.in)
sh-3.2$ echo $f
input: 

```
~/Projects/pick$ f=$(grep "^input: " < tests/01.in)
~/Projects/pick$ echo $f
input: \n
```

What can we do to make this more portable?

Next timeout is on `tests/03.in`. I think it might have something to do with the `\b` but I haven't found a way to debug this.

Do you have any tips for how to best debug this?

**Comment by mptre** [comment]
Calle,

On Fri, Feb 12, 2016 at 02:16:17AM -0800, Calle Erlandsson wrote:
> Very cool, @mptre! Running this on Mac OS X 10.11.2, I get a "time limit exceeded" error on `tests/01.in`. I have tried upping the limit on `tests/test.c:136` but it times out regardless of the limit. I interpret this as pick not understanding the input and not exiting.
> 
> Adding a `#!/usr/bin/env bash` to `tests/test.sh` fixes the time out on `tests/01.in`. My theory is that this has something to do with how `echo` works across `/bin/sh` and `bash`:
> 
> ```
> sh-3.2$ f=$(grep "^input: " < tests/01.in)
> sh-3.2$ echo $f
> input: 
> 
> ```
> ~/Projects/pick$ f=$(grep "^input: " < tests/01.in)
> ~/Projects/pick$ echo $f
> input: \n
> ```
> 
> What can we do to make this more portable?
> 
> Next timeout is on `tests/03.in`. I think it might have something to do with the `\b` but I haven't found a way to debug this.
> 
> Do you have any tips for how to best debug this?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/pull/99#issuecomment-183261648

I've manage to get it running on OS X by rewriting the field parser and removing
platform specific constant. The test runner has now been tested on FreeBSD,
Debian and OS X.

-- 
:wq

**Comment by calleerlandsson** [comment]
Awesome, @mptre! Passes on my machine! After a rebase I think this is ready merge. Maybe we should add these files to `.gitignore`?

```
test-driver
test-suite.log
tests/test
tests/test.sh.log
tests/test.sh.trs
```

**Comment by mptre** [comment]
Agreed, this is ready to be merged. There is still many test cases
missing but I hope that could be a collaborative effort.

Feel free to add the entries to `.gitignore`.

On Fri, Feb 19, 2016 at 05:55:22AM -0800, Calle Erlandsson wrote:
> Awesome, @mptre! Passes on my machine! After a rebase I think this is ready merge. Maybe we should add these files to `.gitignore`?
> 
> ```
> test-driver
> test-suite.log
> tests/test
> tests/test.sh.log
> tests/test.sh.trs
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/pull/99#issuecomment-186222278

-- 
:wq

**Comment by mptre** [comment]
Any plans on getting the test suite to run on Travis? Would be great
since they both support GCC and Clang. While at it: we could make
linting the manpage part of the build process using mandoc(1)[1].

[1] http://mdocml.bsd.lv/man/mandoc.1.html

On Fri, Feb 19, 2016 at 05:55:22AM -0800, Calle Erlandsson wrote:
> Awesome, @mptre! Passes on my machine! After a rebase I think this is ready merge. Maybe we should add these files to `.gitignore`?
> 
> ```
> test-driver
> test-suite.log
> tests/test
> tests/test.sh.log
> tests/test.sh.trs
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/pull/99#issuecomment-186222278

-- 
:wq

**Comment by calleerlandsson** [comment]
Running the suite on Travis would be great, and so would linting the man page be!

**Comment by calleerlandsson** [comment]
I've rebased this, added the mentioned files to `.gitignore`, added `tests/test.sh` to `tests_test_SOURCES` in order to get `make distcheck` to pass, and merged this as 475e1dc040d9cbe9ed445982b24d354d1b47a078, 88876e04e37596fe9909dd9d120a13cac9507fde, 72987aff761071398c18e3b88afcd04497cadb45.

Thanks for your great work, @mptre!

**Pull request closed without merging**
