### PR TITLE
Update README.md.

### PR DESCRIPTION
**Pull request by calleerlandsson**

### CODE REVIEW

**Comment by mike-burns** [comment]
Will you be signing the tarball?

**Comment by calleerlandsson** [comment]
I will and am signing tarballs. Should I add instructions to verify the trails signature?

**Comment by mike-burns** [comment]
Yes, I think that would be a nice addition.

**Comment by mike-burns** [comment]
Let's Go To Malmö.

**Comment by calleerlandsson** [comment]
Going to Malmö.

**Pull request merged**
