### PR TITLE
Pledge on OpenBSD

### PR DESCRIPTION
**Pull request by mptre**
Thoughts @mike-burns?

### CODE REVIEW

**Comment by mike-burns** [comment]
Rad! I'll have to try it later, but quickly: how did you decide on those promises?

**Comment by mptre** [comment]
Start with the empty string. In case of a crash, `dmesg | grep pick`
will tell you which promise is missing, or examine the core-dump using
gdb in order to understand why.

**Comment by mike-burns** [comment]
I played with it and was able to re-pledge before the user can give input. I used ktrace(1) to help:

```
 make && echo "1\n2\n3\n4" | ktrace ./src/pick ; ktrace -C ; kdump > trace && tail trace
```

In which I learned that, by pledging where you pledged:

* `cpath` and `wpath` are needed to open `/dev/tty`.
* `rpath` is needed to open `/usr/share/locale/UTF-8/LC_CTYPE` and then `~/.terminfo`.
* `tty` is needed for the ioctl(2) requesting `TIOCGETA` (and likely others).

So I re-pledged at 177, just before calling `selected_choice()`:

```c
if (pledge("stdio tty", NULL) == -1)
	err(1, "pledge");
```

There, `tty` is needed because `restore_tty()` is called afterward, which uses ioctl(2) requesting `TIOCSETA` (and likely others).

What do you think of pledging twice: once where you did, and again just before `selected_choice()`?

**Comment by mptre** [comment]
> What do you think of pledging twice: once where you did, and again just before `selected_choice()`?

Aiming for the minimal subset of needed promises makes perfect sense.
Good catch!

I updated the patch with your changes and improved the commit-message.

**Comment by mike-burns** [comment]
Nice. Looks good to merge.

**Comment by calleerlandsson** [comment]
That's a cool feature of OpenBSD. Thanks for adding this, @mptre! Merged as 1bf6fb42b5220a217aba9c0e8f26cd9459011441.

**Pull request closed without merging**
