### PR TITLE
Cleanup and missing tests

### PR DESCRIPTION
**Pull request by mptre**
Minor changes this time. Let me know what you think.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Sorry for not getting back to you earlier @mptre, I've been on vacation. I think these changes look great and will merge them!

**Comment by mptre** [comment]
No worries, thanks for merging!

**Comment by calleerlandsson** [comment]
@mptre On that topic: I think the work you're doing on Pick is great and I really appreciate your code contributions as well as your insights on mine and others' PRs.

Would you like to be added as a contributor on this repo with commit access? I think that could streamline our workflow quite a bit by reducing the number of cross-repo PRs in addition to removing me as a bottle-neck for merging PRs while I'm traveling.

**Comment by mptre** [comment]
> Would you like to be added as a contributor on this repo with commit access? I think that could streamline our workflow quite a bit by reducing the number of cross-repo PRs in addition to removing me as a bottle-neck for merging PRs while I'm traveling.

I'd be honored! I don't think the time taken between creation and
merging of a PR is an issue, even when you're on vacation. But not
having to run my own fork with branches would make the process less
tedious. However, I do like our current PR-workflow since every thing
gets reviewed. I guess we would continue with the current workflow but I
would be able to create branches in the pick-repository directly
instead. This also seems compliant with thoughtbot's workflow.

**Comment by calleerlandsson** [comment]
@mptre Great! I've sent an invitation.

I agree that all code that goes into master should go through a PR. I do my best to follow this workflow: https://github.com/thoughtbot/guides/tree/83cfbe7327d574efc1a8943c9e1f60b9af751e1b/protocol/git

> I guess we would continue with the current workflow but I would be able to create branches in the pick-repository directly instead.

Sounds good! After getting a "LGTM" or similar from someone else you'll also be able to rebase and merge your own branches which gets rid of a lot of the "could you please rebase again before I merge" dance.

If you have any questions, don't hesitate to ask me or anyone else; we're happy to answer them!

**Comment by mptre** [comment]
Great! May I add myself as an author to the README and man-page?

**Comment by calleerlandsson** [comment]
Please do! Sorry for not doing it myself earlier.

**Pull request merged**
