### PR TITLE
Undefine __dead before redefining it if necessary

### PR DESCRIPTION
**Pull request by fornwall**
This fixes building for Android.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @fornwall, thanks for contributing!

What is `__dead` defined as for Android? Would it make sense to instead keep the original definition? If so, maybe we should wrap the whole `__dead` combat section in an `#ifndef __dead`?

**Comment by fornwall** [comment]
In `<sys/cdefs.h>`:
```
/* Delete pseudo-keywords wherever they are not available or needed. */
#ifndef __dead
#define __dead
#define __pure
#endif
```

While keeping that empty define would at least not break the build here, perhaps redefining is safer and better in general.

**Comment by calleerlandsson** [comment]
Thanks for finding that!

My understanding is that, if defined, `__dead` will let the compiler optimize functions that never return. Therefor, I think we want to preserve whatever value `__dead` has.

If it is not defined, however, we need to define it in order `pick.c` to compile.

I might be getting this completely wrong, though!

Maybe @mike-burns or @mptre know more about this?

**Comment by mptre** [comment]
> My understanding is that, if defined, `__dead` will let the compiler optimize functions that never return. Therefor, I think we want to preserve whatever value `__dead` has.

Correct.

> If it is not defined, however, we need to define it in order `pick.c` to compile.

Correct.

**Comment by fornwall** [comment]
Ok, should I change the pull request to wrap the whole `__dead`-mangling block (line 8 to 18 in `compat.h`) with `ifndef __dead`?

**Comment by calleerlandsson** [comment]
@fornwall How about we remove line 15 and 16 and add this above `#ifndef HAVE_REALLOCARRAY`:

```
#ifndef __dead
#define __dead
#endif

```

That way we can explicitly define `__dead` to be what we want it to be on systems and compilers we know and let it fall back to whatever it defaults to on other systems that have it and to nothing on systems that don't.

**Comment by fornwall** [comment]
Ah, I should have posted the original problem:

    compat.h:14:0: error: "__dead" redefined

So the problem is that [line 14](https://github.com/thoughtbot/pick/blob/master/src/compat.h#L14) tries to redefine `__dead` without checking if it is already defined.

**Comment by calleerlandsson** [comment]
Oh, right, that makes sense! Let's wrap the whole thing.

**Comment by fornwall** [comment]
I've updated this pull request with a `ifndef __dead` wrapping.

**Comment by calleerlandsson** [comment]
Thanks @fornwall, looks great! I'll merge this.

**Comment by calleerlandsson** [comment]
Merged as 6006a9b.

**Pull request closed without merging**
