### PR TITLE
Remove remaining release tasks

### PR DESCRIPTION
**Pull request by calleerlandsson**
The remaining release tasks don't work well and for the last couple of
releases I've updated the AUR package manually.

Maintaining distribution specific packages outside of the repo creates a
clear separation of concerns.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
This follows up on #135.

**Comment by mike-burns** [comment]
Right on.

Do you want to add a note (to yourself, or for other devs) on how to make an Arch or Homebrew release?

In rcm I keep a list of the package maintainers so that I can contact them when a new release comes out (bottom of https://raw.githubusercontent.com/thoughtbot/rcm/master/DEVELOPERS.md ).

**Comment by calleerlandsson** [comment]
That's a great idea! I'll compile a list.

**Comment by calleerlandsson** [comment]
Hey @xuchunyang @eavgerinos @fornwall @neelchauhan,

I've gone through the commit history of Pick to figure out who's maintaining the different Pick packages in order to compile a list of package maintainers to email about new versions.

Please let me know if you do not want to be listed or no longer want to maintain these packages.

**Comment by calleerlandsson** [comment]
I've emailed the above package maintainers regarding this PR and am waiting for a replies either here or by email.

**Comment by fornwall** [comment]
I'm fine being listed as maintainer for the homebrew package.

**Comment by neelchauhan** [comment]
I'm fine being listed as a maintainer for the FreeBSD port/package.

**Comment by xuchunyang** [comment]
Pick on MacPorts has been updated to latest version v1.4.  Sorry for the delay.

I'm fine being listed as maintainer for the MacPorts port.

**Comment by calleerlandsson** [comment]
Thanks everyone for replying! I've also heard back from @eavgerinos via email so I'll merge this PR now.

**Pull request merged**
