### PR TITLE
Define our own strlcpy if one doesn't exist

### PR DESCRIPTION
**Pull request by Keithbsmiley**
Should fix https://github.com/thoughtbot/pick/issues/6

**Needs to be tested on bsd**

### CODE REVIEW

**Comment by mike-burns** [comment]
Relevant explanations of issues on OS X with strlcpy(3):

https://trac.macports.org/ticket/40763
http://mail-archives.apache.org/mod_mbox/thrift-dev/201310.mbox/%3CJIRA.12672435.1380931512599.101994.1382416363861@arcas%3E

Looks like we should define `_FORTIFY_SOURCE=0` on OS X.

**Comment by calleerlandsson** [comment]
@Keithbsmiley @mike-burns me and @teoljungberg have added some commits that will hopefully fix the build on OS X and FreeBSD and get rid of the warnings on OpenBSD. Could you confirm this?

**Comment by teoljungberg** [comment]
The patches we made worked on my OS X laptop

**Comment by mike-burns** [comment]
Compiles and works on OpenBSD 5.6 with no warnings.

Compiles and works on FreeBSD 9.3 with no warnings.

(I have OpenBSD 5.6 in a VM on my work laptop now, too.)

**Comment by calleerlandsson** [comment]
I have rebased this on master and have made necessary changes. Since this seems to build on all our OSs I'm going to merge this. Thank you.

**Pull request merged**
